// src/app/components/app-sider/index.vue
<script lang="ts" setup>
import { IconChevronLeft, IconChevronRight } from '@tabler/icons-vue';
import PlantManagement from '../../../components/plant-management/index.vue';
import useApp from '../../composables/useApp';
import classes from './style.module.css';

const { activeKey, collapse, setCollapse } = useApp();
</script>

<template>
  <aside :class="classes.sider" :data-collapse="collapse">
    <div :class="classes.button" @click="() => setCollapse(!collapse)">
      <icon-chevron-left v-if="collapse" size="16px" />
      <icon-chevron-right v-else size="16px" />
    </div>
    <div :class="classes.body">
      <plant-management v-if="activeKey === 'plant'" />
    </div>
  </aside>
</template>

// src/app/AppSider/index.tsx
import { useMediaQuery } from '@mantine/hooks';
import { IconChevronLeft, IconChevronRight } from '@tabler/icons-react';
import { useEffect } from 'react';
import PlaneManage from '../../components/PlantManage';
import { useApp } from '../../hooks/useApp';
import classes from './style.module.css';

export default function AppSider() {
	const matches = useMediaQuery('(max-width: 1080px)');

	const { collapse, dispath, active } = useApp();

	useEffect(() => {
		if (matches) dispath({ type: 'collapse', payload: true });
	}, [matches, dispath]);

	return (
		<div
			className={classes.sider}
			style={{
				right: collapse ? -580 : 0,
			}}
		>
			{active}
			<div
				className={classes.button}
				onClick={() => dispath({ type: 'collapse', payload: !collapse })}
			>
				{collapse ? (
					<IconChevronLeft size={16} />
				) : (
					<IconChevronRight size={16} />
				)}
			</div>
			<PlaneManage />
		</div>
	);
}
